services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=taskfin'
      - 'POSTGRES_PASSWORD=bigotes'
      - 'POSTGRES_USER=aldahir'
    ports:
      - '5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
